{/* Current work-around for lack of free nfl player headshots API. */}

const playerPhotoUrls = {
    //p1
    "Christian McCaffrey": "https://a.espncdn.com/i/headshots/nfl/players/full/3117251.png",
    "CeeDee Lamb": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/cqygs9e4ynnjdxstdfjq",
    "Josh Allen": "https://static.www.nfl.com/image/private/t_headshot_desktop/league/ghmmndgjefpxziks7ntf",
    "Tyreek Hill": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3116406.png",
    "Jalen Hurts": "https://static.clubs.nfl.com/image/private/t_editorial_landscape_12_desktop/eagles/lpktrplupwbokng4vxrx",
    "Raheem Mostert": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2576414.png",
    "Amon-Ra St. Brown": "https://a.espncdn.com/i/headshots/nfl/players/full/4374302.png",
    "Dak Prescott": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2577417.png&w=350&h=254",
    "Mike Evans": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/16737.png",
    "Lamar Jackson": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3916387.png",
    "Sam LaPorta": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4430027.png&w=350&h=254",
    "Travis Etienne": "https://static.www.nfl.com/image/private/t_headshot_desktop/league/ne5lyv8n6elqw77yrz9w",
    "Kyren Williams": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4430737.png",
    "Puka Nacua": "https://static.www.nfl.com/image/private/t_headshot_desktop/league/br1ovzclyrebrec6q0mp",
    "D.J. Moore": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3915416.png&w=350&h=254",
    "Derrick Henry": "https://static.www.nfl.com/image/private/t_headshot_desktop/league/xpewyoieoj7zeub4fvff",
    "Joe Mixon": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3116385.png&w=350&h=254",
    "Jordan Love": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4036378.png&w=350&h=254",
    "Breece Hall": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/a6gggxrcgcacgggh0vme",
    "Deebo Samuel": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3126486.png&w=350&h=254",
    //p2
    "A.J. Brown": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4047646.png&w=350&h=254",
    "George Kittle": "https://static.www.nfl.com/image/private/t_headshot_desktop/league/bwx6bvkrxog0yf4h6fw1",
    "Nico Collins": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4258173.png",
    "Rachaad White": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4697815.png&w=350&h=254",
    "Brandon Aiyuk": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360438.png",
    "Travis Kelce": "https://static.www.nfl.com/image/private/t_headshot_desktop/league/ryzr3vbragwe50vtj9af",
    "Keenan Allen": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/15818.png&w=350&h=254",
    "T.J. Hockenson": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4036133.png",
    "Stefon Diggs": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2976212.png&w=350&h=254",
    "David Njoku": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3123076.png&w=350&h=254",
    "Brock Purdy": "https://static.www.nfl.com/image/private/t_headshot_desktop/league/hdwbdlyiose4znenx5ed",
    "David Montgomery": "https://static.www.nfl.com/image/private/t_headshot_desktop/league/grd20lxzonco9jyg3ful",
    "Ja'Marr Chase": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4362628.png&w=350&h=254",
    "Davante Adams": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/16800.png",
    "Jahmyr Gibbs": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4429795.png&w=350&h=254",
    "Evan Engram": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3051876.png",
    "James Cook": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4379399.png",
    "Bijan Robinson": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4430807.png",
    "D.K. Metcalf": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4047650.png&w=350&h=254",
    "Jared Goff": "https://a.espncdn.com/i/headshots/nfl/players/full/3046779.png",
    //p3
    "Taysom Hill": "https://static.www.nfl.com/image/private/t_headshot_desktop/league/pjp1aahvacigoh0sorpg",
    "Amari Cooper": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/zibbxjtein7gpu5zgcj4",
    "Saquon Barkley": "https://static.www.nfl.com/image/private/t_headshot_desktop/league/o8tlhps5u1tvnaaxlpjk",
    "Calvin Ridley": "https://static.www.nfl.com/image/private/t_headshot_desktop/league/jnknuowszoqaywqoopy7",
    "Jayden Reed": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4362249.png&w=350&h=254",
    "Cole Kmet": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4258595.png",
    "Jordan Addison": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4429205.png&w=350&h=254",
    "Jake Ferguson": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4242355.png&w=350&h=254",
    "DeAndre Hopkins": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/15795.png",
    "Patrick Mahomes": "https://static.www.nfl.com/image/private/t_headshot_desktop/league/oagzjdsdoezmp6frggrn",
    "Jakobi Meyers": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3916433.png",
    "James Conner": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3045147.png&w=350&h=254",
    "Gus Edwards": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3051926.png&w=350&h=254",
    "DeVonta Smith": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4241478.png",
    "George Pickens": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4426354.png&w=350&h=254",
    "Trey McBride": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4361307.png&w=350&h=254",
    "Chris Olave": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4361370.png&w=350&h=254",
    "C.J. Stroud": "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4432577.png&w=350&h=254",
    "Kenneth Walker III": "https://static.www.nfl.com/image/private/t_headshot_desktop/league/rwdj1bljth8fyojof5dp",
    "Baker Mayfield": "https://static.www.nfl.com/image/private/t_headshot_desktop/league/haglbmidyaxtimhctzlp",
  };

export default playerPhotoUrls;
